

mybatis:
  # 指定mybatis配置文件的位置
  #config-location: classpath:mapper/mapper-config.xml
  # 指定mapper文件
  mapper-locations: classpath:mapper/mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  # 别名
  type-aliases-package: study.wyy.springboot.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: rootroot
