

mybatis:
  # \u6307\u5B9A\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
  #config-location: classpath:mapper/mapper-config.xml
  # \u6307\u5B9Asql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
  mapper-locations: classpath:mapper/mapper/*.xml
  configuration:
    # \u5F00\u542F\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
  # \u914D\u7F6E\u522B\u540D
  type-aliases-package: study.wyy.springboot.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: rootroot
