

mybatis:
  # \u6307\u5B9A\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
  #config-location: classpath:mapper/mapper-config.xml
  # 指定mapper文件
  mapper-locations: classpath:mapper/mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  # 别名
  type-aliases-package: study.wyy.springboot.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: rootroot
