spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: rootroot
    schema:
     - classpath:department.sql
    type: com.alibaba.druid.pool.DruidDataSource